### ISSUE TITLE
In the real_stereo_pattern.launch file...

### ISSUE THREAD

**Issue by shulace13** [beltransen/velo2cam_calibration#10]
Hi

I'm still struggling with the code but it seems like I need a better calibration board and a stand for it.

Despite that, I noticed that there are two parameters named `min_line_inliers` in line 125 and 131 at the launch file `real_stereo_pattern.launch`
Do I need to keep both of these or could I comment out one of them...

**Comment by beltransen** [comment]
Thanks for the comment, it was a mistake in the file. We have just fixed it, thus you can pull the latest version of the repo and get the updated _.launch_.  However, you may have to adjust this value so that it works with the pointcloud generated by the ZED camera.
