### ISSUE TITLE
fisheye camera pcl_coloring fail

### ISSUE THREAD

**Issue by dbsgws** [beltransen/velo2cam_calibration#13]
Hi,I`m learning velodyne fuse camera in gazebo .

The stereo-camera`s pointcloud coloring works well !

So I try to build a fish-eye camera model to replace stereo-camera in file
and publish correct frame between lidar and camera .

But,there seems something wrong in coloring (haven`t done calibration in fish-eye camera)
![question](https://user-images.githubusercontent.com/32060126/46252759-e96ed880-c49f-11e8-9026-f9f2f4ed8b35.png)

Coloring function only catch the center of image`s point color .
I wonder if the sensor-type doesn`t fit opencv`s function.
Here is my fish-eye camera sdf .

[fpv_cam.txt](https://github.com/beltransen/velo2cam_calibration/files/2431187/fpv_cam.txt)

Hope you can give me some guidance.

**Comment by beltransen** [comment]
Hi @dbsgws, sorry for the late response. We have never worked with fisheye cameras, neither in real life nor in Gazebo simulator. Moreover, we haven't tested our calibration method with this kind of devices. Nonetheless, we think the colouring node should work fine if you are able to provide the proper camera-lidar TF and the correct intrinsic parameters of the camera. Good luck!

**Comment by dbsgws** [comment]
thank you very much!
I have used multi-camera to colorize panorama lidar cloud

**Comment by crankler** [comment]
@dbsgws can you share your experiment for the fisheye ? Thank you!
