### ISSUE TITLE
undefined reference to `pcl::SampleConsensusModelCircle3D<Velodyne::Point>

### ISSUE THREAD

**Issue by anant3110** [beltransen/velo2cam_calibration#2]
CMakeFiles/laser_pattern.dir/src/laser_pattern.cpp.o gets an error while compiling.
All the references to pcl::SampleConsensusModelCircle3d and its member functions are getting an undefined reference.

**Comment by beltransen** [comment]
Hi, can you please give us more info about the console output? We also need to know how are you compiling the repo, and if you have all the required dependencies installed. Which ROS version are you using?

**Comment by anant3110** [comment]
this is the attached log. I am using Indigo.
[log.txt](https://github.com/beltransen/velo2cam_calibration/files/1025476/log.txt)

**Comment by beltransen** [comment]
In the log there is no error, neither pcl::SampleConsensusModelCircle3D is never mentioned. Maybe this is not the full console log?

**Comment by anant3110** [comment]
Sorry, My bad!
[log1.txt](https://github.com/beltransen/velo2cam_calibration/files/1025508/log1.txt)

**Comment by cguindel** [comment]
Could you please check if the PCL variables are correctly set by the CMakeLists when you run catkin_make?, namely PCL_LIBRARY_DIRS, PCL_DEFINITIONS, etc. It seems to be a problem with your PCL setup.

**Comment by anant3110** [comment]
I checked out the CMakeLists.txt and everything seems to be fine. The problem here is that every other cpp file is getting compiled except laser_pattern.cpp

**Comment by anant3110** [comment]
[CMakeLists.txt](https://github.com/beltransen/velo2cam_calibration/files/1028591/CMakeLists.txt)

**Comment by beltransen** [comment]
Could you please show what's inside the PCL variables while compiling? This can be done through by calling the MESSAGE() function in the CMakeLists file. The package is working fine in Ubuntu 16.04 and ROS Kinetic, as validated by ROS repository indexer, so it is likely a compatibility issue with your PCL setup.

**Comment by anant3110** [comment]
Is there anyway that you can propose that it works with ROS Indigo and Ubuntu 14.04? 
Our project is working on that version only.

**Comment by beltransen** [comment]
We have just compiled the package in an Ubuntu 14.04 computer with ROS Indigo and we got no errors. Make sure you have installed all the dependencies successfully or try to compile it on another computer, as it seems to be all right. Please, keep us up to date with any progress

**Comment by anant3110** [comment]
I ended up using Ubuntu 16.04 only.
