### ISSUE TITLE
Does the algorithm support a calibration plate that is not vertical?

### ISSUE THREAD

**Issue by duchengyao** [beltransen/velo2cam_calibration#21]
The calibration plate is not perpendicular to the camera and causes four ellipse instead of round. Does this algorithm support this situation?

Thanks

**Comment by beltransen** [comment]
Hi @duchengyao, the calibration target doesn't have to be placed perpendicular to the camera as we are not using image features to detect the target circles, but the stereo point cloud instead. Thus, as we are working with 3D information, circles can be found regardless the position of the calibration board (given a reasonable angle where the holes can be properly identified from the camera point of view).

**Comment by duchengyao** [comment]
Thanks so much (`・ω・´)
