### ISSUE TITLE
Kinetic make fail

### ISSUE THREAD

**Issue by bsridatta** [beltransen/velo2cam_calibration#22]
For gcc version 6.5.0 20181026 (Ubuntu 6.5.0-2ubuntu1~16.04) 
Many **error: unable to find numeric literal operator ‘operator""Q’**

/usr/include/boost/math/special_functions/detail/erf_inv.hpp:354:46: 
error: unable to find numeric literal operator ‘operator""Q’
          if(is_value_non_zero(static_cast<T>(BOOST_MATH_BIG_CONSTANT(T, 64, 1e-900))))

Any suggestions to get around this problem?

**Comment by bsridatta** [comment]
Found similar issues elsewhere and got it to build fine using

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DBOOST_MATH_DISABLE_FLOAT128")
in the cmakelist

**Comment by bsridatta** [comment]
Please let me know if it is a good way to do this. I am not able to get a proper image overlay with the given simulation rosbag

**Comment by beltransen** [comment]
Hi @bsridatta, we are not sure which is the problem now. Are you still having any compilation issues?

**Comment by bsridatta** [comment]
Hi @beltransen, Thanks for response, we moved to Melodic and it is working fine. I will close the issue
