### ISSUE TITLE
Can this pkg be used for VLP16 and D435i or t265?

### ISSUE THREAD

**Issue by crankler** [beltransen/velo2cam_calibration#28]
I undistort the t265 camera and try to use this pkg, but I cann't get a goog result? have someone try with t265 or D435i? thank you!

**Comment by cguindel** [comment]
Hi @crankler,

The method has not been tested with those cameras, but, in principle, there should not be any problem. Please check #26 for tips on how you can adapt the code to your needs.

If you need more help, please describe your problem more accurately.

**Comment by crankler** [comment]
Yes, I have tried to tune  some parameters as you suggest,  and I cann't see the point cloud from camera.
I will try again to adapt my sensor. Thank you again for your help!
