### ISSUE TITLE
cannot launch node of type *

### ISSUE THREAD

**Issue by anant3110** [beltransen/velo2cam_calibration#3]
After Doing
`roslaunch velo2cam_calibration stereo_pattern.launch'
A lot of errors pop up saying that nodes were not found. i.e.
[disparity/disparity_node], opencv_apps/edge_detection], pcl_utils/disp_masker], [calibration_from_plane/plane_segmentation].

**Comment by cguindel** [comment]
Sorry, you are totally right; we were using our own unreleased dependencies. Thank you for the heads-up. 9abff1a7f6535df6a896219724fc51310288aa5c should fix it. You will also have to install [opencv_apps](http://wiki.ros.org/opencv_apps) from the ROS repositories:
```shell
sudo apt-get install ros-kinetic-opencv-apps
```
Please, check it and tell us if there is anything else wrong.

**Comment by anant3110** [comment]
It works! Thank You so much!
