### ISSUE TITLE
Can it be used with rgbd?

### ISSUE THREAD

**Issue by Mikor-mkr** [beltransen/velo2cam_calibration#33]
Hello,
 thank you for taking the time to check my post. I want to ask if I can use this package with rgbd camera, or if I can feed the pointcloud of the rgbd instead using the stereo topic to create the pointcloud.
 
 Thank you in advance!

**Comment by cguindel** [comment]
Sure, you can just remove all the `stereo_image_proc` nodelets from `stereo_pattern.launch` and publish your pointcloud as (or remap it to) `$(arg camera_name)/points2`. You will also need to generate somehow an "edges pointcloud" where only the points corresponding to high intensity levels in the Sobel image (`edge_detection/image`) are included, and publish it as `$(arg camera_name)/edge_points2`.

You might need to tune some parameters to fit the properties of the new pointcloud, but I believe that no major changes will be needed.
