### ISSUE TITLE
Can I use this program with Hokuyo3d lidar and usb web cam ?

### ISSUE THREAD

**Issue by konnoeric** [beltransen/velo2cam_calibration#37]
I am considering to use 3DLiDAR from Hokuyo (YVT-X002) and a usb web camera from ELECOM UCAM-C520FEBK. Is this applicable? What should I concern about when using these?

**Comment by cguindel** [comment]
Hi @konnoeric. Our tool is intended to be functional with all kinds of cameras and multi-layer LiDAR scanners, but we cannot provide personalized support for every device. Please follow the instructions in our HOWTO document and report any issue to us.
