### ISSUE TITLE
Is this pacakage able to color point cloud or project point cloud on to image?

### ISSUE THREAD

**Issue by konnoeric** [beltransen/velo2cam_calibration#38]
I have not tried the program yet but can I color the point cloud or project point clouds on the image like the photos of your tutorials [here](http://wiki.ros.org/velo2cam_calibration) in Overview section?

**Comment by cguindel** [comment]
Hi again, @konnoeric. We implemented nodes performing those functions in our previous v1.0 codebase, but dropped support in v2.0 to reduce the complexity of the package and focus our efforts on the main application. However, you can check the cpp files implementing these nodes (pcl_projection.cpp and pcl_coloring.cpp) in [v1.0](https://github.com/beltransen/velo2cam_calibration/tree/v1.0/src). Please use them as you see fit.
