### ISSUE TITLE
liadr pattern exit code -11

### ISSUE THREAD

**Issue by zaxii** [beltransen/velo2cam_calibration#40]
Excuse me. I was trying this calibration with RS-Ruby(RS128) and a mono camera online.
I use tools to change /rslidar_points into /velodyne_points online. 
I succeed use 

`roslaunch velo2cam_calibration mono_pattern.launch camera_name:=/blackflys image_topic:=image_color frame_name:=blackflys`

But the next 

`roslaunch velo2cam_calibration lidar_pattern.launch cloud_topic:=/velodyne_points`

will fail and exit code -11 as soon as I publish /velodyne_points.

I check the log and I am really confused.

I also tried to record /velodyne_points and camera infos into bag. Then try this calibration offline. But the results are the same.

The log is below, i hope to get some help T T.

`[roslaunch][INFO] 2021-10-24 19:38:09,955: ... created process [lidar_pattern_0-5]

[roslaunch.pmon][INFO] 2021-10-24 19:38:09,955: ProcessMonitor.register[lidar_pattern_0-5]

[roslaunch.pmon][INFO] 2021-10-24 19:38:09,955: ProcessMonitor.register[lidar_pattern_0-5] complete

[roslaunch][INFO] 2021-10-24 19:38:09,955: ... registered process [lidar_pattern_0-5]

[roslaunch][INFO] 2021-10-24 19:38:09,955: process[lidar_pattern_0-5]: starting os process

[roslaunch][INFO] 2021-10-24 19:38:09,955: process[lidar_pattern_0-5]: start w/ args [[u'/home/bulldog/catkin_ws/devel/lib/velo2cam_calibration/lidar_pattern', u'~cloud1:=/lidar_pattern_0/zyx_filtered', u'__name:=lidar_pattern_0', u'__log:=/home/bulldog/.ros/log/0ef8c3a8-34ba-11ec-95e1-ef78d46f8dbc/lidar_pattern_0-5.log']]

[roslaunch][INFO] 2021-10-24 19:38:09,955: process[lidar_pattern_0-5]: cwd will be [/home/bulldog/.ros]

[roslaunch][INFO] 2021-10-24 19:38:09,966: process[lidar_pattern_0-5]: started with pid [6739]

[roslaunch][INFO] 2021-10-24 19:38:09,967: ... successfully launched [lidar_pattern_0-5]

[roslaunch][INFO] 2021-10-24 19:38:09,967: ... launch_nodes complete

[roslaunch.pmon][INFO] 2021-10-24 19:38:09,967: registrations completed <ProcessMonitor(ProcessMonitor-1, started daemon 140333577279232)>

[roslaunch.parent][INFO] 2021-10-24 19:38:09,967: ... roslaunch parent running, waiting for process exit

[roslaunch][INFO] 2021-10-24 19:38:09,967: spin

[roslaunch][ERROR] 2021-10-24 19:38:11,644: [lidar_pattern_0-5] process has died [pid 6739, exit code -11, cmd /home/bulldog/catkin_ws/devel/lib/velo2cam_calibration/lidar_pattern ~cloud1:=/lidar_pattern_0/zyx_filtered __name:=lidar_pattern_0 __log:=/home/bulldog/.ros/log/0ef8c3a8-34ba-11ec-95e1-ef78d46f8dbc/lidar_pattern_0-5.log].
log file: /home/bulldog/.ros/log/0ef8c3a8-34ba-11ec-95e1-ef78d46f8dbc/lidar_pattern_0-5*.log

[roslaunch.pmon][INFO] 2021-10-24 19:38:11,644: ProcessMonitor.unregister[lidar_pattern_0-5] starting

[roslaunch.pmon][INFO] 2021-10-24 19:38:11,644: ProcessMonitor.unregister[lidar_pattern_0-5] complete`

**Comment by cguindel** [comment]
Hi @zaxii, 

Could you please try changing the value of the `rings_count` parameter [here](https://github.com/beltransen/velo2cam_calibration/blob/a26164200a38cb9211f000e7606e400fdfc67ceb/src/lidar_pattern.cpp#L530) to 128? 

This is not properly documented as we weren't expecting lidar scanners with more than 64 layers, but if it solves your problem, we may take action.

Thank you.

**Comment by zaxii** [comment]
@cguindel 
Thank you for the help！
There are some other work for me to do, so it takes such a long time for me to retry this calibration. Sorry for that.
After changing this and making a same calibration board, i got the result of the RS-Ruby and one camera of Ladybug 5p.
The calibration process is convenient, I just need to use some projection methods to verify the result.
By the way, **do you have any recommendations for projection methods?**
Thank you again for the help!

**Comment by cguindel** [comment]
We are glad you found our package helpful. For the projection of LiDAR points onto the image, I recommend RVIZ through the native ['Camera' display type](http://wiki.ros.org/rviz/DisplayTypes/Camera). As long as both sensors are synchronized, it will use the estimated TF to render the 3D points of the active PointCloud2 within the camera output.  

If that option does not fit your needs, you can also implement a custom projection module; in #38, we provided some information about a projection node included in previous versions of our package, which you might find interesting.
