### ISSUE TITLE
Sorry, how to prepare a calibration board 

### ISSUE THREAD

**Issue by ThinkPig826** [beltransen/velo2cam_calibration#41]
Does the calibration board have to be the same as the one introduced in the project?

**Comment by cguindel** [comment]
Hi @ThinkPig826,

In principle, the main idea of our paper can be applied to other calibration patterns, but that will obviously require extensive modifications to the code of this package to make it functional. If you can stick at least to the design with four circles and change only the dimensions, you may just need to tune some parameters as discussed [here](https://github.com/beltransen/velo2cam_calibration/issues/39#issuecomment-915966344]). 

On the other hand, the calibration target that we propose can be manufactured in many different ways; we recommend a rigid material to avoid flexing (e.g., rigid PVC, wood, etc.), but, apart from that, there are really no other restrictions.
