### ISSUE TITLE
verification of the calibration 

### ISSUE THREAD

**Issue by talhasu** [beltransen/velo2cam_calibration#46]
Hi,
Thank you for your wonderful package. I have completed the process and was able to get the following output (see attached screenshot). I am wondering how can I know that the calibration actually worked. Do your package allow live verification? Is there a way to know if the point cloud from lidar is merging with the image from your package?

![Screenshot from 2022-06-10 13-43-15](https://user-images.githubusercontent.com/62899649/173210593-025d2559-dbbb-46b4-840f-9b8d811d8d06.png)

**Comment by cguindel** [comment]
Currently, we do not provide tools to project the LiDAR point cloud onto the image; instead, we recommend using native ROS apps: if you run the resulting _calibrated_tf.launch_ and your sensors are correctly synchronized, you can use a Camera display in RVIZ to check the result.

**Comment by talhasu** [comment]
"you can use a Camera display in RVIZ to check the result." By result, do you mean that we should be able to see the projected cloud on the image? Can you please explain with a screenshot or something? 
Do you mean that I need to keep the calibrated_tf.launch file running and check the camera display?

**Comment by cguindel** [comment]
Yes, you need to run the calibrated_tf.launch to broadcast the tf between the two sensors, and then RVIZ will listen to that tf and project the cloud onto the image, as long as the LiDAR cloud is being shown. You can check this example:

![default rviz- - RViz_002](https://user-images.githubusercontent.com/15200248/174760854-4a1c9939-f98f-4f96-85d1-11cfcfcec538.png)

**Comment by SueeH** [comment]
> Hi, Thank you for your wonderful package. I have completed the process and was able to get the following output (see attached screenshot). I am wondering how can I know that the calibration actually worked. Do your package allow live verification? Is there a way to know if the point cloud from lidar is merging with the image from your package?
> 
> ![Screenshot from 2022-06-10 13-43-15](https://user-images.githubusercontent.com/62899649/173210593-025d2559-dbbb-46b4-840f-9b8d811d8d06.png)

Where can I find the test datase( or rosbag)?

**Comment by cguindel** [comment]
@SueeH Sorry, we do not provide test data at the moment. 

Closing the issue as it seems solved.
