### ISSUE TITLE
I don't achieve precission claimed in paper with M>3 and M<=5

### ISSUE THREAD

**Issue by Nasrudin78** [beltransen/velo2cam_calibration#47]
Hello,
I'm trying to calibrate a pinhole camera and HDL32 lidar (both rendered in Gazebo) . I'm using different panels orientations and positions of the included pattern. The result in translation -after registration- is quite good, but in rotation, there are values that are greater than 1 degree -compared with the HDL32 ground truth rendered in Gazebo -.
I've tested with 3 up to 5 different pattern poses,tilts and distances (avoiding co-planarity) but without any success in lowering rotation differences below 1 degree.
Is it possible to minimize even more the difference < 1 degree? 
Thanks for your contribution and help.

**Comment by cguindel** [comment]
It is difficult for us to guess the possible causes of the discrepancy you have observed in your tests, as many factors can be involved. One of them is the location of the calibration pattern: if it is too far away from the sensors, the performance may be degraded. To discard other sources of error, maybe you can try to replicate the Single-Sensor Experiments from our T-ITS paper (the relative target-sensor positions that we used are reported in Table III) and make sure that the errors in the location of the reference points are within the range of those shown in Figures 4 and 5.

**Comment by Nasrudin78** [comment]
Hello again,
I've tried to mimic your 5 poses environment using pinhole + hdl64 (mono_hdl64_p1_sX_real.launch) [Setting X = [1..5]) 
In order to compare results qualitatively, I've compared the true Lidar Hd64 position and rotation in Gazebo (that corresponds to xyz:='-0.3 0.2 1.8' rpy:='0.3 -0.1 0.2'  **[1]** in .launch file) versus the result of velo2cam registration : 
```
x = 0.2766      y = -0.1921     z = 0.2309
roll = -0.3177  pitch = 0.0329  yaw = -0.2223
```
that  expressed in World coordinates (Ego car) yields : T =  -0.31499671,   0.14693794, 1.78573126 and
R= 0.20177555, -0.09951528,0.30394539  **[2]**

Focusing only in Rotation vector (R) and applying absolute difference btw  Ground truth [1] and estimated rotation vector after registration [2], there are differences of >5degrees in Roll and Yaw.

Is there something wrong in my assessment?
Thanks in advance

**Comment by Nasrudin78** [comment]
Hi,
Finally I discovered the error source. I swapped values in  Yaw and Roll rotation components during the basis change process.
With only 1 panel the error is below 0.2 degrees in the rotation vector.
Thanks for your help!
