### ISSUE TITLE
pattern_circles point cloud is sparse

### ISSUE THREAD

**Issue by lbouz102** [beltransen/velo2cam_calibration#51]
ZYX filtered cloud:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/33760138/183766525-ee8af23c-31b6-424f-959a-080f85c3b766.png)

Range filtered cloud:
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/33760138/183766551-b39dfb88-9119-4214-834b-ca1c5693002e.png)

Pattern circles:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/33760138/183766586-dc4242f3-ac6a-4252-b551-7f5c67d83922.png)

There seems to be an issue in the plane segmentation or edge detection step that is causing my pattern_cloud to appear incorrect. My target is the exact same geometry as the diagram in the GitHub readme and it has a wall behind it >10cm away. I've adjusted the following parameters as outlined in the HowTo:
- pass_through_radius_[min/max]
- pass_through_[x,y,z]_velo_[min/max]

I've also tried individually adjusting:
- angle_threshold_
- plane_threshold_
- gradient_threshold_
- plane_distance_inliers_
- circle_threshold_
- target_radius_tolerance_

I'm unsure on how to proceed in debugging because it seems like its a problem with the sac segmentation step. Can you provide more insight into what I should be expecting visually in the pattern_clouds or what other parameters to adjust?

**Comment by cguindel** [comment]
I don't know what is happening here, but I would like to figure it out. Could you send us a bag file with a snippet of your data so we can reproduce the issue? If you prefer, you can send it by email; my address is in the [paper](https://arxiv.org/abs/2101.04431).

**Comment by lbouz102** [comment]
It ended up being an issue with how I was sending the point cloud. I misunderstood the requirement that the ring Ids were necessary in order to search for the edges. Since all my points were labeled ring 0 it was detecting "random" points as edges. My pattern circle cloud now looks much better:
![Screenshot from 2022-08-30 14-31-16](https://user-images.githubusercontent.com/33760138/187516281-0ffad4f8-4e08-4662-b75d-b3a2442e3d01.png)

I am still having an issue where > 4 circles are being detected and it doesn't fit the target geometry ~95% of the time. The screenshot above is good example of one where the hole centers are often not detected. Do you have any suggestions for parameters I can tune or is this just a product of the 32-channel VLP not having enough points?

**Comment by cguindel** [comment]
Thanks for your reply. Interestingly, that is not the behavior we observed when all the points were assigned ring 0. In that case, every point is treated as if they belong to a single ring, and the search for "jumps" is done along that very long ring, which could cause some noise, but nothing that problematic. Is it possible that the ring values were just assigned randomly before?

Regarding your current result, the VLP-32 should definitely be dense enough for the method to work. However, your pattern_circles cloud does not look as expected. It should be something similar to this:

![image](https://user-images.githubusercontent.com/15200248/187648168-586a7cf7-bbb7-4317-9f13-f28d0a82159e.png)

That is, after the edge extraction procedure, there should be a single point representing the edges of the pattern, as we do not perform accumulation at that stage. However, in your case, it seems like you have small clusters instead. So I think the source of the problem could still be in the data, but I can't say if it is still related to the ring field or comes from elsewhere.

**Comment by lbouz102** [comment]
I didn't define the rings field in my sensor_msg so its possible that it was randomly assigned to whatever values were in memory? I'll look at this again to clarify for you once I've solved the other issue.

Yes, you're right that I have small clusters. I aggregated the Velodyne data before sending it because I thought it would help with the circle detection. After your response I realize this isn't the correct approach so I've removed that and I'm still having the same issues. Here is my pattern circle cloud now:
![Screenshot from 2022-08-31 12-33-12](https://user-images.githubusercontent.com/33760138/187731480-9540ba53-c71c-457a-bada-3eeecc61f363.png)

The only way I'm able to get some centers correct is if I increase my target_radius_tolerance to 0.02. I've remeasured my target to ensure the dimensions are correct. It doesn't seem like its an issue with the quality of data as its comparable to what you've shown.

NOTE: The reason there aren't edges detected on both sides is this cloud was recorded outside and I had to hold a board behind the holes.

Thank you for all the assistance!

**Comment by cguindel** [comment]
Hi @lbouz102, could you solve the issue? Did you obtain good results after tuning the target_radius_tolerance parameter?

**Comment by lbouz102** [comment]
This issue was resolved by reducing the RPM of the velodyne (1200 to 300). The edge points on the circle didn't form a clean circle as shown in the picture above. Feel free to close this issue as the initial post was a misunderstanding that an ordered point cloud is needed. Thanks!

**Comment by cguindel** [comment]
Ok, thank you for your reply; it is good to be aware of that caveat for future reference. 

Closing the issue as suggested.
