### ISSUE TITLE
Question about Lidar coordinate base system

### ISSUE THREAD

**Issue by Nasrudin78** [beltransen/velo2cam_calibration#53]
My question is about the lidar coordinate base system resulting from the camera to lidar registration. The results from the registration algorithm are linked to the Lidar bottom base or the Lidar laser ray beam?
Thank you

**Comment by beltransen** [comment]
Hi @Nasrudin78, the results are linked to the Lidar ray beam and, in the case of camera sensors, to the optical center.

**Comment by cguindel** [comment]
Closing the issue due to inactivity. Feel free to reopen it if you need it.
