### ISSUE TITLE
HOW TO GET THE GROUND-TRUTH

### ISSUE THREAD

**Issue by gyt290811** [beltransen/velo2cam_calibration#56]
hi, I got this problem how to calculate the ground-truth to verify this calibration result. So   I want to know you how to get the ground-truth as you referred in your paper?????? 

Thank you!

**Comment by cguindel** [comment]
In our paper, we use ground truth in the simulation environment only. You can find the corresponding Gazebo models, plugins and worlds at https://github.com/beltransen/velo2cam_gazebo
