### ISSUE TITLE
calibration board size

### ISSUE THREAD

**Issue by MingiJeong** [beltransen/velo2cam_calibration#72]
Hi. Thanks for this good contribution.
Out of curiousity, do you think it would work if I shrink the size and marker to the half of your original size (1400, 1000)?

**Comment by beltransen** [comment]
Hi @MingiJeong. The specifics of your setup, such as the LiDAR model (including the number of planes and their distribution) and the operating distance, play a crucial role. It's essential for each hole in the board to be visible from at least two LiDAR rings. Therefore, the smaller the board, the closer it needs to be positioned to the sensors.
